import { FireBaseDocument, ProductBundleType } from '@/app/utils/types';
import { Timestamp } from 'firebase/firestore';

export const emptyProductBundleInitialState: ProductBundleType & FireBaseDocument = {
    exist: false,
    id: '',
    categories: [''],
    collections: [],
    description: '',
    estoqueTotal: 0,
    images: [{ localUrl: '', index: 0 }],
    slug: '',
    name: '',
    randomIndex: '00',
    productVariations: [
        {
            barcode: '',
            categories: [''],
            collections: [],
            dimensions: { altura: 0, comprimento: 0, largura: 0 },
            estoque: 0,
            image: '',
            name: '',
            peso: 0,
            productId: '',
            sku: '',
            value: { cost: 0, price: 0, promotionalPrice: 0 },
            sections: [],
            subsections: [],
        },
    ],
    sections: [''],
    subsections: [''],
    showProduct: false,
    freeShipping: false,
    lancamento: false,
    value: { cost: 0, price: 0, promotionalPrice: 0 },
    finalPrice: 0,
    promotional: false,
    creationDate: Timestamp.now(),
    updatingDate: Timestamp.now(),
};