// app/layout.tsx
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Footer from './components/Footer';
import Header from './components/Header';
import { AuthContextProvider } from './context/AuthContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Alexa Semi-Joias',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={ inter.className }>
                <AuthContextProvider>
                    <Header>
                        { children }
                    </Header>
                    <Footer />
                </AuthContextProvider>
            </body>
        </html>
    );
}
