import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import Footer from './components/Footer';
import Header from './components/header/Header';
import { AuthContextProvider } from './context/AuthContext';
import { UserInfoProvider } from './context/UserInfoContext';
import { Analytics } from '@vercel/analytics/react';
import { SpeedInsights } from '@vercel/speed-insights/next';

const inter = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Alexa Semi-Joias',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <meta name="facebook-domain-verification" content="k9qc45dlpt6m4sxg6a3qmin2rmabmh" />
            </head>
            <body className={ `${inter.className} min-h-screen bg-[#FAF9F6]` }>
                <AuthContextProvider>
                    <UserInfoProvider>
                        <Header />
                        { children }
                        <Footer />
                    </UserInfoProvider>
                </AuthContextProvider>
                <Analytics />
                <SpeedInsights />
            </body>
        </html>
    );
}
