export const emptyUserTypeInitialState = {
    exist: false,
    id: '',
    nome: '',
    email: '',
    userId: '',
    cpf: '',
    tel: '',
    admin: false,
    address: {
        bairro: '',
        cep: '',
        complemento: '',
        ddd: '',
        gia: '',
        ibge: '',
        localidade: '',
        logradouro: '',
        numero: '',
        siafi: '',
        uf: '',
        unidade: '',
        referencia: '',
    },
};